spring.application.name=demo
# MongoDB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=attendance_db

# Server configuration (changing default port)
server.port=8081